public class BM_TaskStatus {

	public static final String NOT_STARTED = 'Новая';
	public static final String IN_PROGRESS = 'Выполняется';
	public static final String COMPLETED = 'Завершено';
	public static final String DEFERRED = 'Отложено';
	public static final String REOPENED = 'Переоткрыто';

	public static final String[] ACTIVE_TASK_STATUSES = new String[] {NOT_STARTED, IN_PROGRESS, REOPENED};

}